"""Canonical schema constants for the customer retention pipeline.

These values intentionally mirror the Phase 1 database contracts and workbook
labels from the customer retention SRS. Runtime ingestion and workbook behavior
should import these constants instead of duplicating string literals.
"""

from __future__ import annotations

LEAD_SOURCE_RETENTION = "RETENTION"
LEAD_SOURCE_TD = "TD"
LEAD_SOURCE_EXTERNAL = "EXTERNAL"
LEAD_SOURCE_TYPES = (
    LEAD_SOURCE_RETENTION,
    LEAD_SOURCE_TD,
    LEAD_SOURCE_EXTERNAL,
)

LEAD_STATUS_OPEN = "OPEN"
LEAD_STATUS_PENDING = "PENDING"
LEAD_STATUS_DUE_FOLLOWUP = "DUE_FOLLOWUP"
LEAD_STATUS_WORKED = "WORKED"
LEAD_STATUS_CLOSED = "CLOSED"
LEAD_STATUS_RECOVERED = "RECOVERED"
LEAD_STATUS_SUPPRESSED = "SUPPRESSED"
LEAD_STATUS_STALE = "STALE"
LEAD_STATUS_ERROR = "ERROR"
LEAD_STATUSES = (
    LEAD_STATUS_OPEN,
    LEAD_STATUS_PENDING,
    LEAD_STATUS_DUE_FOLLOWUP,
    LEAD_STATUS_WORKED,
    LEAD_STATUS_CLOSED,
    LEAD_STATUS_RECOVERED,
    LEAD_STATUS_SUPPRESSED,
    LEAD_STATUS_STALE,
    LEAD_STATUS_ERROR,
)

LIFECYCLE_BUCKET_ACTIVE = "ACTIVE"
LIFECYCLE_BUCKET_WARM = "WARM"
LIFECYCLE_BUCKET_COOLING = "COOLING"
LIFECYCLE_BUCKET_DORMANT = "DORMANT"
LIFECYCLE_BUCKET_COLD = "COLD"
LIFECYCLE_BUCKET_LOST = "LOST"
LIFECYCLE_BUCKETS = (
    LIFECYCLE_BUCKET_ACTIVE,
    LIFECYCLE_BUCKET_WARM,
    LIFECYCLE_BUCKET_COOLING,
    LIFECYCLE_BUCKET_DORMANT,
    LIFECYCLE_BUCKET_COLD,
    LIFECYCLE_BUCKET_LOST,
)

SUPPRESSION_STATE_ACTIVE = "ACTIVE"
SUPPRESSION_STATE_PENDING_APPROVAL = "PENDING_APPROVAL"
SUPPRESSION_STATE_REJECTED = "REJECTED"
SUPPRESSION_STATE_EXPIRED = "EXPIRED"
SUPPRESSION_STATES = (
    SUPPRESSION_STATE_ACTIVE,
    SUPPRESSION_STATE_PENDING_APPROVAL,
    SUPPRESSION_STATE_REJECTED,
    SUPPRESSION_STATE_EXPIRED,
)

CAP_WORK_SECTION_DUE_FOLLOWUP = "DUE_FOLLOWUP"
CAP_WORK_SECTION_PENDING_CARRY_FORWARD = "PENDING_CARRY_FORWARD"
CAP_WORK_SECTION_TD_LEAD = "TD_LEAD"
CAP_WORK_SECTION_EXTERNAL_LEAD = "EXTERNAL_LEAD"
CAP_WORK_SECTION_FRESH_RETENTION = "FRESH_RETENTION"
CAP_WORK_SECTIONS = (
    CAP_WORK_SECTION_DUE_FOLLOWUP,
    CAP_WORK_SECTION_PENDING_CARRY_FORWARD,
    CAP_WORK_SECTION_TD_LEAD,
    CAP_WORK_SECTION_EXTERNAL_LEAD,
    CAP_WORK_SECTION_FRESH_RETENTION,
)
CAP_CONFIG_WORK_SECTIONS = (
    CAP_WORK_SECTION_TD_LEAD,
    CAP_WORK_SECTION_EXTERNAL_LEAD,
    CAP_WORK_SECTION_FRESH_RETENTION,
)

WORKBOOK_OUTCOME_NO_RESPONSE = "No Response"
WORKBOOK_OUTCOME_SWITCHED_OFF = "Switched Off"
WORKBOOK_OUTCOME_WRONG_NUMBER = "Wrong Number"
WORKBOOK_OUTCOME_WHATSAPP_SENT = "WhatsApp Sent"
WORKBOOK_OUTCOME_INTERESTED = "Interested"
WORKBOOK_OUTCOME_WILL_GIVE_ORDER_LATER = "Will Give Order Later"
WORKBOOK_OUTCOME_PICKUP_REQUESTED = "Pickup Requested"
WORKBOOK_OUTCOME_ALREADY_GIVEN_ORDER = "Already Given Order"
WORKBOOK_OUTCOME_PRICE_ISSUE = "Price Issue"
WORKBOOK_OUTCOME_SERVICE_COMPLAINT = "Service Complaint"
WORKBOOK_OUTCOME_USING_COMPETITOR = "Using Competitor"
WORKBOOK_OUTCOME_SHIFTED_LOCATION = "Shifted Location"
WORKBOOK_OUTCOME_NOT_INTERESTED = "Not Interested"
WORKBOOK_OUTCOME_DO_NOT_CONTACT = "Do Not Contact"
WORKBOOK_OUTCOME_INVALID_NUMBER = "Invalid Number"
WORKBOOK_OUTCOME_LEAD_STALE = "Lead Stale"
WORKBOOK_OUTCOME_LABELS = (
    WORKBOOK_OUTCOME_NO_RESPONSE,
    WORKBOOK_OUTCOME_SWITCHED_OFF,
    WORKBOOK_OUTCOME_WRONG_NUMBER,
    WORKBOOK_OUTCOME_WHATSAPP_SENT,
    WORKBOOK_OUTCOME_INTERESTED,
    WORKBOOK_OUTCOME_WILL_GIVE_ORDER_LATER,
    WORKBOOK_OUTCOME_PICKUP_REQUESTED,
    WORKBOOK_OUTCOME_ALREADY_GIVEN_ORDER,
    WORKBOOK_OUTCOME_PRICE_ISSUE,
    WORKBOOK_OUTCOME_SERVICE_COMPLAINT,
    WORKBOOK_OUTCOME_USING_COMPETITOR,
    WORKBOOK_OUTCOME_SHIFTED_LOCATION,
    WORKBOOK_OUTCOME_NOT_INTERESTED,
    WORKBOOK_OUTCOME_DO_NOT_CONTACT,
    WORKBOOK_OUTCOME_INVALID_NUMBER,
    WORKBOOK_OUTCOME_LEAD_STALE,
)
PERMANENT_SUPPRESSION_WORKBOOK_OUTCOMES = (
    WORKBOOK_OUTCOME_DO_NOT_CONTACT,
    WORKBOOK_OUTCOME_WRONG_NUMBER,
    WORKBOOK_OUTCOME_INVALID_NUMBER,
    WORKBOOK_OUTCOME_SHIFTED_LOCATION,
)
TIME_BOUND_SUPPRESSION_WORKBOOK_OUTCOMES = (
    WORKBOOK_OUTCOME_NOT_INTERESTED,
    WORKBOOK_OUTCOME_LEAD_STALE,
)
