UPDATE store_master SET store_name = 'Madhu Vihar, Delhi' WHERE store_code = 'T154';
UPDATE store_master SET store_name = 'Janakpuri, Delhi' WHERE store_code = 'T166';
UPDATE store_master SET store_name = 'Dwarka Expressway, Gurgaon' WHERE store_code = 'T412';
UPDATE store_master SET store_name = 'Sector 14, Gurgaon' WHERE store_code = 'T594';
UPDATE store_master SET store_name = 'Shashtri Nagar, Delhi' WHERE store_code = 'T997';
UPDATE store_master SET store_name = 'Punjabi Bagh, Delhi' WHERE store_code = 'TS27';
UPDATE store_master SET store_name = 'South City, Gurgaon' WHERE store_code = 'TS48';
UPDATE store_master SET store_name = 'COCO Warehouse, Gurgaon' WHERE store_code = 'TS62';
UPDATE store_master SET store_name = 'Sector 83, Gurgaon' WHERE store_code = 'TS72';
UPDATE store_master SET store_name = 'Qutub Paza, Gurgaon' WHERE store_code = 'A717';
UPDATE store_master SET store_name = 'Dhankot CC, Gurgaon' WHERE store_code = 'A745';
UPDATE store_master SET store_name = 'Kirti Nagar, Delhi' WHERE store_code = 'A817';
UPDATE store_master SET store_name = 'Ashok Vihar, Delhi' WHERE store_code = 'B002';
UPDATE store_master SET store_name = 'M3M Urbana, Gurgaon' WHERE store_code = 'T105';
UPDATE store_master SET store_name = 'Palam Vihar, Gurgaon' WHERE store_code = 'T137';
UPDATE store_master SET store_name = 'Sector 3, Rohini, Delhi' WHERE store_code = 'A012';
UPDATE store_master SET store_name = 'Preet Vihar, Delhi' WHERE store_code = 'T201';
UPDATE store_master SET store_name = 'Chhatarpur, Delhi' WHERE store_code = 'T210';
UPDATE store_master SET store_name = 'Hauz Khas, Delhi' WHERE store_code = 'TS71';
UPDATE store_master SET store_name = 'NFC, Delhi' WHERE store_code = 'TS74';
UPDATE store_master SET store_name = 'Vasant Kunj, Delhi' WHERE store_code = 'TS81';
UPDATE store_master SET store_name = 'Saket, Delhi' WHERE store_code = 'TS86';
UPDATE store_master SET store_name = 'Sector 93, Gurgaon' WHERE store_code = 'A040';
UPDATE store_master SET store_name = 'Vijay Nagar, Delhi' WHERE store_code = 'A142';
UPDATE store_master SET store_name = 'Vikaspuri, Delhi' WHERE store_code = 'A276';
UPDATE store_master SET store_name = 'Sohna, Gurgaon' WHERE store_code = 'A398';
UPDATE store_master SET store_name = 'Tilak Nagar, Delhi' WHERE store_code = 'A526';
UPDATE store_master SET store_name = 'Model Town, Delhi' WHERE store_code = 'A572';
UPDATE store_master SET store_name = 'Uttam Nagar, Delhi' WHERE store_code = 'A668';
UPDATE store_master SET store_name = 'Nazafgarh , Delhi' WHERE store_code = 'A674';
UPDATE store_master SET store_name = 'Supermart, Gurgaon' WHERE store_code = 'A696';
UPDATE store_master SET store_name = 'Old Rajender Nagar, Delhi' WHERE store_code = 'TS36';